// Stub for @/routes (generated by @laravel/vite-plugin-wayfinder at build time).
// Returns a no-op for any named export so tests don't fail on missing routes.
export default new Proxy(
    {},
    {
        // eslint-disable-next-line @typescript-eslint/no-unused-vars
        get: (_target, _prop) => () => '#',
    },
);

export const logout = () => '/logout';
